site_name: aequos Modern Data Visualizer solution for SharePoint Online
nav:
    - Getting Started:
        - Introduction: getting_started.md
        - Get and deploy the solution:  get_and_install_solution.md
        - Activate standalone license: setup_standalone.md
    - Data Visualizer:
      - Usage: basic/usage/data-visualizer/introduction.md
      - Data sources: basic/usage/data-visualizer/data-sources/index.md
      - Slots: basic/usage/data-visualizer/slots.md
      - Tokens: basic/usage/data-visualizer/tokens.md
      - Layouts: basic/usage/data-visualizer/layouts/index.md
      - Connections: basic/usage/data-visualizer/connections/index.md
      - Extensibility: basic/usage/data-visualizer/extensibility/index.md
    - Data Filters:
      - Usage: basic/usage/data-filters/introduction.md
      - Layouts: basic/usage/data-filters/layouts/index.md
    - Data Verticals:
      - Usage: basic/usage/data-verticals/introduction.md 
    - Search Box:
      - Usage: basic/usage/search-box/introduction.md
    - Extensibility:
      - Introduction: basic/extensibility/introduction.md
      - Templating: basic/extensibility/templating.md
      - Custom data source: basic/extensibility/custom_data_source.md
      - Custom layout: basic/extensibility/custom_layout.md
      - Custom web component: basic/extensibility/custom_web_component.md
      - Custom suggestions provider: basic/extensibility/custom_suggestions_provider.md
      - Custom Handlebars customizations: basic/extensibility/introduction.md
    - Frequently Asked Questions: faq.md
theme:
  name: 'material'
  palette:
    primary: 'black'
  feature:
    tabs: true
  logo: 'assets/aequos_logo.png'
  font:
    code: 'Ubuntu Mono'
extra_css:
  - 'assets/extra.css'
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - markdown_include.include:
          base_path: docs
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/aequos_ca'
    - type: 'link'
      link: 'www.aequos.ca'
repo_url: https://github.com/aequos-solutions/aequos.github.io
edit_uri: blob/master/docs