site_name: aequos Modern Data Visualizer solution for SharePoint Online
nav:
    - Introduction: index.md
    - Getting Started:
        - Get and deploy the solution:  getting_started/get_and_install-solution.md
        - Activate standalone license: getting_started/setup_standalone.md
        - Available data sources: getting_started/builtin_datasources.md
        - Available layouts: getting_started/builtin_layouts.md
    - Data Visualizer:
      - Usage: basic/usage/data-visualizer/introduction.md
      - Data sources: basic/usage/data-visualizer/data-sources/index.md
      - Slots: basic/usage/data-visualizer/slots.md
      - Tokens: basic/usage/data-visualizer/tokens.md
      - Layouts: basic/usage/data-visualizer/layouts/index.md
      - Connections: index.md
      - Extensibility: index.md
    - Frequently Asked Questions: faq.md
theme:
  name: 'material'
  palette:
    primary: 'black'
  feature:
    tabs: true
  logo: 'assets/aequos_logo.png'
  font:
    code: 'Ubuntu Mono'
extra_css:
  - 'assets/extra.css'
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - markdown_include.include:
          base_path: docs
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/aequos_ca'
    - type: 'link'
      link: 'www.aequos.ca'
repo_url: https://github.com/aequos-solutions/aequos.github.io
edit_uri: blob/master/docs